// const env = import.meta.env;
// const MOVIEDB_KEY = env.VITE_MOVIEDB_KEY;
// const OPENWEATHERMAP_KEY = env.VITE_OPENWEATHERMAP_KEY;
// const NYTAPIKEY = env.VITE_NYTAPIKEY;

// export { MOVIEDB_KEY, NYTAPIKEY, OPENWEATHERMAP_KEY };


const MOVIEDB_KEY = import.meta.env.VITE_MOVIEDB_KEY;
const OPENWEATHERMAP_KEY = import.meta.env.VITE_OPENWEATHERMAP_KEY;
const NYTAPIKEY = import.meta.env.VITE_NYTAPIKEY;

export { MOVIEDB_KEY, NYTAPIKEY, OPENWEATHERMAP_KEY };
